#!/bin/sh

set -e

echo "====> Checking homebrew dependencies..."
brew bundle check &>/dev/null || {
  brew update >/dev/null
  brew bundle
}

echo "====> Installing heroku plugins..."
heroku plugins | grep heroku-docker >/dev/null ||
  heroku plugins:install heroku-docker

echo 'Done!'
